"""Renders project_verification_certificate.md and .pdf FROM project_verification_certificate.json
-- the JSON is the single source of truth; both other formats are derived views of it, so
they cannot disagree with each other or with the JSON."""
from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

with open(PROJECT_ROOT / "project_verification_certificate.json") as f:
    c = json.load(f)

def yn(b: bool) -> str:
    return "PASS" if b else "FAIL"

def check_mark(b: bool) -> str:
    return "[x]" if b else "[ ]"

# ===========================================================================
# Markdown
# ===========================================================================
md = []
md.append("# Project Verification Certificate")
md.append("")
md.append(f"**Document type**: {c['document_type']}  ")
md.append(f"**Generated (UTC)**: {c['generated_at_utc']}  ")
md.append(f"**Generated by**: {c['generated_by']}")
md.append("")
md.append("> This is the authoritative, fact-checked record of the exact submission artifact "
           "produced by this project. Every value below was computed or read directly from "
           "repository artifacts and live command output at certificate-generation time -- "
           "none are estimated. See `project_verification_certificate.json` for the "
           "machine-readable source this document was rendered from.")
md.append("")
md.append("---")

# --- Repository ---
r = c["repository"]
md.append("## Repository Information")
md.append("")
md.append(f"| Field | Value |")
md.append(f"|---|---|")
md.append(f"| Repository name | `{r['repository_name']}` |")
md.append(f"| Git branch | `{r['git_branch']}` |")
md.append(f"| Final commit hash | `{r['final_commit_hash']}` |")
md.append(f"| Release tag | `{r['release_tag']}` |")
md.append(f"| Release tag → commit (verified match) | `{r['release_tag_commit_hash']}` |")
md.append(f"| Commit timestamp | {r['commit_timestamp']} |")
md.append(f"| Working tree clean at certificate-build time | {r['working_tree_clean_at_certificate_time']} (new fact-gathering files for this certificate were added and committed alongside it) |")
md.append("")

# --- Environment ---
e = c["environment"]
md.append("## Environment")
md.append("")
md.append(f"| Field | Value |")
md.append(f"|---|---|")
md.append(f"| Python version | {e['python_version']} |")
md.append(f"| Operating system | {e['operating_system']} {e['os_release']} ({e['os_version']}) |")
md.append(f"| Architecture | {e['architecture']} |")
md.append(f"| Platform string | `{e['platform_string']}` |")
md.append(f"| `requirements_frozen.txt` SHA-256 | `{e['requirements_frozen_sha256']}` |")
md.append(f"| Random seed | {e['random_seed']} |")
md.append(f"| Random seed scope | {e['random_seed_scope']} |")
md.append("")
md.append("**Key package versions** (read live from the installed environment):")
md.append("")
md.append("| Package | Version |")
md.append("|---|---|")
for pkg, ver in e["package_versions"].items():
    md.append(f"| {pkg} | {ver} |")
md.append("")

# --- Final Model ---
fm = c["final_model"]
md.append("## Final Model")
md.append("")
md.append(f"**Architecture**: {fm['architecture']}")
md.append("")
md.append(f"**Feature configuration**: `{fm['feature_configuration']['feature_set_name']}` set, "
           f"{fm['feature_configuration']['n_features']} features: "
           f"{', '.join(fm['feature_configuration']['features'])}")
md.append("")
md.append("**Base models**:")
md.append("")
for name, spec in fm["base_models"].items():
    md.append(f"- **{name}** ({spec['family']}) — feature_set=`{spec['feature_set']}`, scaler=`{spec['scaler']}`")
    md.append(f"  - Hyperparameters: `{spec['hyperparameters']}`")
md.append("")
md.append(f"**Ensemble weights** (fixed linear combination, fit out-of-fold — Phase 6):")
md.append("")
md.append("| Base model | Coefficient |")
md.append("|---|---|")
for k, v in fm["ensemble_weights"].items():
    md.append(f"| {k} | {v:.6f} |")
md.append(f"| *intercept* | {fm['ensemble_intercept']:.6f} |")
md.append("")
md.append(f"**Clipping policy**: [{fm['clipping_policy']['lower_bound']}, {fm['clipping_policy']['upper_bound']}] — "
           f"{fm['clipping_policy']['rationale']}")
md.append("")
sa = fm["serialized_artifact"]
md.append(f"**Serialized artifact**: `{sa['path']}` ({sa['size_bytes']:,} bytes) — SHA-256: `{sa['sha256']}`")
md.append("")

# --- Validation Protocol ---
vp = c["final_validation_protocol"]
md.append("## Final Validation Protocol")
md.append("")
md.append(f"- **Primary reporting protocol**: {vp['primary_reporting_protocol']} — {vp['total_folds']} total folds ({vp['n_folds_per_repeat']} folds × {vp['n_repeats']} repeats)")
md.append(f"- **Final ensemble protocol**: {vp['final_ensemble_protocol']}")
md.append(f"- **Hyperparameter search protocol**: {vp['hyperparameter_search_protocol']}")
md.append(f"- **Protocol selection justification**: {vp['protocol_selection_justification']}")
md.append("")
md.append("**Statistical tests performed across the project**:")
md.append("")
for t in vp["statistical_tests_performed"]:
    md.append(f"- {t}")
md.append("")

# --- Final Performance ---
fp = c["final_performance"]
md.append("## Final Performance")
md.append("")
fe = fp["final_ensemble"]
bs = fp["best_single_model_baseline"]
db = fp["dummy_regressor_baseline"]
md.append("| Model | RMSE | MAE | R² | Protocol |")
md.append("|---|---|---|---|---|")
md.append(f"| Dummy (predict mean) | {db['rmse_mean']:.3f} ± {db['rmse_std']:.3f} | {db['mae_mean']:.3f} ± {db['mae_std']:.3f} | {db['r2_mean']:.4f} | {db['protocol']} |")
md.append(f"| Best single model ({bs['model']}) | {bs['rmse_mean']:.3f} | {bs['mae_mean']:.3f} | {bs['r2_mean']:.4f} | {bs['protocol']} |")
md.append(f"| **Final ensemble** | **{fe['rmse_mean']:.3f} ± {fe['rmse_std']:.3f}** | **{fe['mae_mean']:.3f} ± {fe['mae_std']:.3f}** | **{fe['r2_mean']:.4f} ± {fe['r2_std']:.4f}** | {fe['protocol']} |")
md.append("")
md.append(f"- **Improvement over dummy baseline**: {fp['percentage_improvement_over_dummy_baseline']}%")
md.append(f"- **Improvement over best single model**: {fp['percentage_improvement_over_best_single_model']}%")
md.append("")
ci = fp["confidence_interval_vs_best_single_model"]
md.append(f"**Statistical comparison vs. best single model** ({ci['comparison']}):")
md.append("")
md.append(f"- Mean RMSE difference: {ci['mean_rmse_difference']:.4f}")
md.append(f"- Paired t-test p-value: {ci['paired_t_p_value']:.2e}")
md.append(f"- Wilcoxon signed-rank p-value: {ci['wilcoxon_p_value']:.4f}")
md.append(f"- 95% bootstrap confidence interval: [{ci['bootstrap_95pct_ci'][0]:.4f}, {ci['bootstrap_95pct_ci'][1]:.4f}]")
md.append(f"- CI excludes zero (statistically significant): **{ci['ci_excludes_zero']}**")
md.append("")

# --- Artifact Inventory ---
md.append("## Artifact Inventory")
md.append("")
md.append("| Filename | Purpose | Size | SHA-256 |")
md.append("|---|---|---|---|")
for a in c["artifact_inventory"]:
    size = f"{a['size_bytes']:,} bytes" if a["size_bytes"] else "MISSING"
    md.append(f"| `{a['filename']}` | {a['purpose']} | {size} | `{a['sha256'][:24]}...` |")
md.append("")

# --- Submission Verification ---
sv = c["submission_verification"]
md.append("## Submission Verification")
md.append("")
md.append("| Check | Status | Note |")
md.append("|---|---|---|")
for key, val in sv.items():
    if key == "final_submission_sha256":
        continue
    label = key.replace("_", " ").capitalize()
    md.append(f"| {label} | {yn(val['status'])} | {val['note']} |")
md.append("")
md.append(f"**Final submission SHA-256**: `{sv['final_submission_sha256']}`")
md.append("")

# --- Validation Checklist ---
md.append("## Validation Checklist")
md.append("")
for item in c["validation_checklist"]:
    md.append(f"- {check_mark(item['status'])} {item['item']}")
md.append("")

# --- Known Limitations ---
md.append("## Known Limitations")
md.append("")
md.append("(Copied from the Phase 9 independent adversarial audit — no new limitations invented for this certificate.)")
md.append("")
for i, lim in enumerate(c["known_limitations"], 1):
    md.append(f"**{i}. {lim['description']}**")
    md.append("")
    md.append(f"- *Evidence*: {lim['evidence']}")
    md.append(f"- *Expected impact*: {lim['expected_impact']}")
    md.append(f"- *Mitigation*: {lim['mitigation']}")
    md.append("")

# --- Risk Register ---
md.append("## Risk Register")
md.append("")
md.append("(Residual risks remaining after the Phase 9 audit's fixes.)")
md.append("")
md.append("| Risk | Likelihood | Impact | Mitigation | Residual Risk |")
md.append("|---|---|---|---|---|")
for row in c["risk_register"]:
    md.append(f"| {row['risk']} | {row['likelihood']} | {row['impact']} | {row['mitigation']} | {row['residual_risk']} |")
md.append("")

# --- Certification Statement ---
md.append("## Certification Statement")
md.append("")
md.append(f"> {c['certification_statement']}")
md.append("")

# --- Final Recommendation ---
fr = c["final_recommendation"]
md.append("## Final Recommendation")
md.append("")
md.append(f"# {fr['recommendation']}")
md.append("")
if fr["required_actions"]:
    md.append("**Required administrative action(s)**:")
    md.append("")
    for action in fr["required_actions"]:
        md.append(f"1. {action}")
md.append("")

md_text = "\n".join(md)
with open(PROJECT_ROOT / "project_verification_certificate.md", "w", encoding="utf-8") as f:
    f.write(md_text)
print("Wrote project_verification_certificate.md")
