"""Renders project_verification_certificate.pdf from the same JSON source of truth, via a
styled HTML intermediate (xhtml2pdf) -- a polished, presentation-ready layout distinct from
the plain Markdown, but reporting identical facts."""
from __future__ import annotations

import json
from pathlib import Path

from xhtml2pdf import pisa

PROJECT_ROOT = Path(__file__).resolve().parents[1]

with open(PROJECT_ROOT / "project_verification_certificate.json") as f:
    c = json.load(f)


def esc(s) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def status_badge(ok: bool) -> str:
    color = "#1a7f37" if ok else "#c0392b"
    text = "PASS" if ok else "FAIL"
    return f'<span style="color:{color};font-weight:bold;">{text}</span>'


r, e, fm, vp, fp = c["repository"], c["environment"], c["final_model"], c["final_validation_protocol"], c["final_performance"]

html_parts = []
html_parts.append(f"""
<html>
<head>
<style>
  @page {{ size: A4; margin: 2.2cm 1.8cm; }}
  body {{ font-family: Helvetica, Arial, sans-serif; font-size: 9.5pt; color: #1a1a1a; line-height: 1.45; }}
  h1 {{ font-size: 20pt; color: #0b3d63; border-bottom: 3px solid #0b3d63; padding-bottom: 8px; margin-bottom: 4px; }}
  h2 {{ font-size: 13pt; color: #0b3d63; margin-top: 20px; border-bottom: 1px solid #cccccc; padding-bottom: 3px; }}
  h3 {{ font-size: 10.5pt; color: #333333; margin-top: 10px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 8px 0; }}
  th {{ background-color: #0b3d63; color: white; padding: 4px 6px; text-align: left; font-size: 8.5pt; }}
  td {{ padding: 4px 6px; border-bottom: 1px solid #dddddd; font-size: 8.5pt; vertical-align: top; }}
  tr:nth-child(even) {{ background-color: #f4f7fa; }}
  .mono {{ font-family: Courier, monospace; font-size: 7.5pt; word-break: break-all; }}
  .badge-box {{ background-color: #eef6ee; border: 2px solid #1a7f37; padding: 14px; margin: 14px 0; text-align: center; }}
  .badge-title {{ font-size: 16pt; font-weight: bold; color: #1a7f37; }}
  .cert-quote {{ background-color: #f4f7fa; border-left: 4px solid #0b3d63; padding: 10px 14px; margin: 10px 0; font-size: 9pt; font-style: italic; }}
  .subtitle {{ color: #555555; font-size: 10pt; margin-bottom: 14px; }}
  .footer-note {{ color: #888888; font-size: 7.5pt; margin-top: 24px; border-top: 1px solid #cccccc; padding-top: 6px; }}
</style>
</head>
<body>

<h1>Project Verification Certificate</h1>
<div class="subtitle">
  Document type: {esc(c['document_type'])}<br/>
  Generated (UTC): {esc(c['generated_at_utc'])}<br/>
  Generated by: {esc(c['generated_by'])}
</div>

<p><i>This is the authoritative, fact-checked record of the exact submission artifact produced
by this project. Every value in this document was computed or read directly from repository
artifacts and live command output at certificate-generation time.</i></p>

<h2>1. Repository Information</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>Repository name</td><td class="mono">{esc(r['repository_name'])}</td></tr>
<tr><td>Git branch</td><td class="mono">{esc(r['git_branch'])}</td></tr>
<tr><td>Final commit hash</td><td class="mono">{esc(r['final_commit_hash'])}</td></tr>
<tr><td>Release tag</td><td class="mono">{esc(r['release_tag'])}</td></tr>
<tr><td>Tag -&gt; commit (verified match)</td><td class="mono">{esc(r['release_tag_commit_hash'])}</td></tr>
<tr><td>Commit timestamp</td><td>{esc(r['commit_timestamp'])}</td></tr>
</table>

<h2>2. Environment</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>Python version</td><td>{esc(e['python_version'])}</td></tr>
<tr><td>Operating system</td><td>{esc(e['operating_system'])} {esc(e['os_release'])}</td></tr>
<tr><td>Architecture</td><td>{esc(e['architecture'])}</td></tr>
<tr><td>requirements_frozen.txt SHA-256</td><td class="mono">{esc(e['requirements_frozen_sha256'])}</td></tr>
<tr><td>Random seed</td><td>{esc(e['random_seed'])}</td></tr>
</table>
<table>
<tr><th>Package</th><th>Version</th></tr>
{''.join(f"<tr><td>{esc(k)}</td><td>{esc(v)}</td></tr>" for k, v in e['package_versions'].items())}
</table>

<h2>3. Final Model</h2>
<p><b>Architecture:</b> {esc(fm['architecture'])}</p>
<p><b>Feature configuration:</b> {esc(fm['feature_configuration']['feature_set_name'])} set,
{fm['feature_configuration']['n_features']} features:
{esc(', '.join(fm['feature_configuration']['features']))}</p>

<table>
<tr><th>Base model</th><th>Ensemble weight</th></tr>
{''.join(f"<tr><td>{esc(k)}</td><td>{v:.6f}</td></tr>" for k, v in fm['ensemble_weights'].items())}
<tr><td><i>intercept</i></td><td>{fm['ensemble_intercept']:.6f}</td></tr>
</table>
<p><b>Clipping policy:</b> [{fm['clipping_policy']['lower_bound']}, {fm['clipping_policy']['upper_bound']}]</p>
<p><b>Serialized artifact:</b><br/>
<span class="mono">{esc(fm['serialized_artifact']['path'])}</span><br/>
{fm['serialized_artifact']['size_bytes']:,} bytes -- SHA-256: <span class="mono">{esc(fm['serialized_artifact']['sha256'])}</span></p>

<h2>4. Final Validation Protocol</h2>
<p><b>Primary reporting protocol:</b> {esc(vp['primary_reporting_protocol'])} ({vp['total_folds']} total folds)</p>
<p><b>Final ensemble protocol:</b> {esc(vp['final_ensemble_protocol'])}</p>
<p><b>Statistical tests performed:</b> {esc(', '.join(vp['statistical_tests_performed']))}</p>

<h2>5. Final Performance</h2>
<table>
<tr><th>Model</th><th>RMSE</th><th>MAE</th><th>R2</th></tr>
<tr><td>Dummy (predict mean)</td><td>{fp['dummy_regressor_baseline']['rmse_mean']:.3f} +/- {fp['dummy_regressor_baseline']['rmse_std']:.3f}</td><td>{fp['dummy_regressor_baseline']['mae_mean']:.3f}</td><td>{fp['dummy_regressor_baseline']['r2_mean']:.4f}</td></tr>
<tr><td>Best single model ({esc(fp['best_single_model_baseline']['model'])})</td><td>{fp['best_single_model_baseline']['rmse_mean']:.3f}</td><td>{fp['best_single_model_baseline']['mae_mean']:.3f}</td><td>{fp['best_single_model_baseline']['r2_mean']:.4f}</td></tr>
<tr style="background-color:#eef6ee;"><td><b>Final ensemble</b></td><td><b>{fp['final_ensemble']['rmse_mean']:.3f} +/- {fp['final_ensemble']['rmse_std']:.3f}</b></td><td><b>{fp['final_ensemble']['mae_mean']:.3f}</b></td><td><b>{fp['final_ensemble']['r2_mean']:.4f}</b></td></tr>
</table>
<p><b>Improvement over dummy baseline:</b> {fp['percentage_improvement_over_dummy_baseline']}%<br/>
<b>Improvement over best single model:</b> {fp['percentage_improvement_over_best_single_model']}%</p>
<p><b>Statistical significance vs. best single model:</b> paired t-test p={fp['confidence_interval_vs_best_single_model']['paired_t_p_value']:.2e},
95% CI=[{fp['confidence_interval_vs_best_single_model']['bootstrap_95pct_ci'][0]:.3f}, {fp['confidence_interval_vs_best_single_model']['bootstrap_95pct_ci'][1]:.3f}]
(excludes zero: {fp['confidence_interval_vs_best_single_model']['ci_excludes_zero']})</p>
""")

def short_path(p: str, max_len: int = 34) -> str:
    """xhtml2pdf's table engine does not reliably support table-layout:fixed / colgroup
    widths, nor does it widen a column for nowrap content -- long text in one cell can
    visually overlap the next column regardless (a confirmed renderer limitation, not a
    config error; tested table-layout:fixed, colgroup widths, and white-space:nowrap, all
    ineffective). The reliable fix combines HTML4-attribute column widths (which this
    ReportLab-based engine DOES respect) with truncating cell content to fit inside them."""
    return p if len(p) <= max_len else "..." + p[-(max_len - 3):]

# Artifact inventory (compact) -- HTML4 width= attributes, not CSS, are what xhtml2pdf's
# table engine actually honors reliably.
html_parts.append("""<h2>6. Artifact Inventory</h2>
<table>
<tr><th width="33%">Filename</th><th width="30%">Purpose</th><th width="12%">Size</th><th width="25%">SHA-256 (prefix)</th></tr>""")
for a in c["artifact_inventory"]:
    size = f"{a['size_bytes']:,} B" if a["size_bytes"] else "MISSING"
    html_parts.append(f"<tr><td class='mono'>{esc(short_path(a['filename']))}</td><td>{esc(a['purpose'])}</td><td>{size}</td><td class='mono'>{esc(a['sha256'][:16])}...</td></tr>")
html_parts.append("</table>")

# Submission verification
html_parts.append("<h2>7. Submission Verification</h2><table><tr><th>Check</th><th>Status</th><th>Note</th></tr>")
for key, val in c["submission_verification"].items():
    if key == "final_submission_sha256":
        continue
    html_parts.append(f"<tr><td>{esc(key.replace('_',' ').capitalize())}</td><td>{status_badge(val['status'])}</td><td>{esc(val['note'])}</td></tr>")
html_parts.append(f"</table><p><b>Final submission SHA-256:</b> <span class='mono'>{esc(c['submission_verification']['final_submission_sha256'])}</span></p>")

# Validation checklist
html_parts.append("<h2>8. Validation Checklist</h2><table><tr><th>Item</th><th>Status</th></tr>")
for item in c["validation_checklist"]:
    html_parts.append(f"<tr><td>{esc(item['item'])}</td><td>{status_badge(item['status'])}</td></tr>")
html_parts.append("</table>")

# Known limitations
html_parts.append("<h2>9. Known Limitations</h2>")
for i, lim in enumerate(c["known_limitations"], 1):
    html_parts.append(f"<h3>{i}. {esc(lim['description'])}</h3>")
    html_parts.append(f"<p><i>Evidence:</i> {esc(lim['evidence'])}<br/>"
                       f"<i>Expected impact:</i> {esc(lim['expected_impact'])}<br/>"
                       f"<i>Mitigation:</i> {esc(lim['mitigation'])}</p>")

# Risk register
html_parts.append("<h2>10. Risk Register</h2><table><tr><th>Risk</th><th>Likelihood</th><th>Impact</th><th>Residual Risk</th></tr>")
for row in c["risk_register"]:
    html_parts.append(f"<tr><td>{esc(row['risk'])}</td><td>{esc(row['likelihood'])}</td><td>{esc(row['impact'])}</td><td>{esc(row['residual_risk'])}</td></tr>")
html_parts.append("</table>")

# Certification statement
html_parts.append(f"""
<h2>11. Certification Statement</h2>
<div class="cert-quote">{esc(c['certification_statement'])}</div>

<h2>12. Final Recommendation</h2>
<div class="badge-box">
  <div class="badge-title">{esc(c['final_recommendation']['recommendation'])}</div>
</div>
""")

if c["final_recommendation"]["required_actions"]:
    html_parts.append("<p><b>Required administrative action(s):</b></p><ol>")
    for action in c["final_recommendation"]["required_actions"]:
        html_parts.append(f"<li>{esc(action)}</li>")
    html_parts.append("</ol>")

html_parts.append(f"""
<div class="footer-note">
Rendered from project_verification_certificate.json (single source of truth for all 3
certificate formats). Repository: {esc(r['repository_name'])} | Commit: {esc(r['final_commit_hash'][:12])} |
Tag: {esc(r['release_tag'])}
</div>
</body>
</html>
""")

html = "".join(html_parts)
html_path = PROJECT_ROOT / "project_verification_certificate_render.html"
with open(html_path, "w", encoding="utf-8") as f:
    f.write(html)

pdf_path = PROJECT_ROOT / "project_verification_certificate.pdf"
with open(pdf_path, "wb") as f:
    result = pisa.CreatePDF(html, dest=f)

if result.err:
    print(f"PDF generation reported {result.err} error(s)")
else:
    print(f"Wrote {pdf_path}")
